apiVersion: v1
kind: Service
metadata:
  name: student-dashboard-service
spec:
  type: NodePort
  selector:
    app: student-dashboard
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
